### ISSUE TITLE
[FEATURE] 인식된 음식에 따라 재료 추출 로직 구현 

### ISSUE THREAD

**Issue by jeongjaino** [Team-HealthC/HealthC_Android#101]
## 📑 작업 사항 
인식된 음식에 따라 재료 추출 로직 구현 

인식된 다중 음식 - 리사이클 뷰로 보여주기 
사용자가 선택한 음식 - 재료 추출 로직 보여주기 (음식에 따른 재료 테이블 구현 && Firestore GET 로직 구현) 
재료에 따라 먹을 수 있는 음식인지 아닌지 보여주기 

## To-do
- [x] 인식된 음식 리스트 뷰 구현
- [x] Firestore 테이블 재료 테이블 구현
- [x] 음식에 따라 재료 가져오는 로직 구현 
- [x] 사용자 알러지에 따라 먹을 수 있는 음식인지 아닌지 판별 기능 구현 

# #✔️ 기타사항

**Comment by jeongjaino** [comment]
다시 돌고 ~ 또 돌 고 ~
