### ISSUE TITLE
[FEATURE] 음식 인식 UI 업데이트 

### ISSUE THREAD

**Issue by jeongjaino** [Team-HealthC/HealthC_Android#102]
## 📑 작업 사항 
음식을 인식하고, 재료를 도출, 사용자 먹을 수 있는 음식인지 확인하는 화면 모두 UI 업데이트 

공통 구현 사항 - TopBar 구현, Dialog -> 따로 화면 구현 

## To-do
- [ ] 인식된 음식 보여주는 화면 UI 수정  
- [ ] 사용자가 먹을 수 있는 음식인지 판별하는 화면 UI 수정 
- [ ] 객체 인식하는 애니메이션 Lottie 가져오기 

# #✔️ 기타사항
